### ISSUE TITLE
Receive emails on actions to cards

### ISSUE THREAD

**Issue by cheerios911** [go-vikunja/frontend#11]
Problem:  When assigning a card to a user that works well, however when that user does something on a card, a comment, adds a new sub-task; there is no notification at all that it has transpired.

As a result, we have users commenting on issues and it goes un-noticed for weeks on end.  Is there a way to enable notification via email on these types of actions?

Emails work well for the reminder emails, but there is nothing for actual actions that take place.  

Edit: i would have commented on the gitea repo, but I can't get the email confirmation to actually get sent to me to create an account.

**Comment by kolaente** [comment]
>  Is there a way to enable notification via email on these types of actions?

These kinds of notifications are currently not implemented so just enabling them won't work :upside_down_face: 

I have this in the [backlog](https://my.vikunja.cloud/share/QFyzYEmEYfSyQfTOmIRSwLUpkFjboaBqQCnaPmWd/auth) since quite while, just moved it up. There are multiple ways on how to implement this and I'd like to have clean way to be able to extend it in the future. Also this is kind of related to "events" which I'd like to have eventually - but that's a whole other big topic. I think these kinds of notifications should be to implement as well. I think it's doable and already have a rough idea how to achieve it, but it won't be that easy. Doable, but it will take a while.

> Edit: i would have commented on the gitea repo, but I can't get the email confirmation to actually get sent to me to create an account.

Sure, we can discuss that here as well. I think there was an issue with the mail server sending the confirmation mails hmmm. The joys of using your own infrastructure :grinning: 

Have you tried using the github authentication?

**Comment by cheerios911** [comment]
> I'd like to have clean way to be able to extend it in the future. 

Makes sense, and I understand.  I think an easy way to go about this is to perhaps implement the ability to '@' a user in a comment or description.  This way when user A comments on task 1, user A can ping user B with @userb or something of that nature.  But yes, i don't want to be blasted with mail, but i do need to know when a user does something.  A catch 22 if you will lol.

> I'm currently busy with this release but may include this in the one after that. I don't really want to promise anything here but I think a rough version of that could be possible to achieve.

That's great news, i'm excited to see the next update.  When my developer gets back on vacation, we will send you the fix we implemented for the CSS issues when you load a background image.

> github authentication?

yes lol, that exactly what i tried after.  I will try later and see if i get the confirmation mail.

**Comment by kolaente** [comment]
Mentioning other users in comments is something I plan to do as well (I have way too much things planned).

> When my developer gets back on vacation, we will send you the fix we implemented for the CSS issues when you load a background image.

CSS fixes sound awesome - I'm always happy to take pull requests 😄
Frontend-wise, the release after the upcoming one will be a lot about improving the frontend so that will probably fit right in.

> We are working on implementing Vikunja into our calDAV / event system.

Awesome! Is the system already visible somewhere?

Also just curious, how are you using Vikunja? Do the team / sharing features work for you or are there things to improve (other than the email notifications)?

**Comment by cheerios911** [comment]
> (I have way too much things planned). 

LOL, same boat mate, same boat.

> CSS fixes sound awesome - I'm always happy to take pull requests

He get's back monday, i'll have him fire over when he's back from vacation.  

> Is the system already visible somewhere?

It is yes, but we are reworking the frontend now that we are about to integrate your system in.  Send me a PM and we can do a quick demo (we are going to release it opensource as well)

> how are you using Vikunja? Do the team / sharing features work for you or are there things to improve

1. Personal Tasks / CalDAV into my android (tasks app)
2. team management, but we are struggling with emails (but we may solve that in our integration as we run an opensource mail system)
3. client management - my favorite part of this to let clients view and edit tasks without account.  it's a huge help for us

for the most part everything works wonderfully from what we need, you've built I think is the best task manager that is out there and I love how you built this structurally. The UI is nice, but what is wonderful is the API's and that the frontend isn't mandatory.  that's something most people just don't think of in advance. 🙏 👀

**Comment by kolaente** [comment]
>  Send me a PM and we can do a quick demo

I'd love to! I couldn't find any personal information of you to send you a PM though, did I overlook something? You can reach me at hello@vikunja.io though, maybe that would work.

> for the most part everything works wonderfully from what we need, you've built I think is the best task manager that is out there and I love how you built this structurally. The UI is nice, but what is wonderful is the API's and that the frontend isn't mandatory. that's something most people just don't think of in advance. 

Really awesome to hear that, thanks for the kind words! That really is the part that's the most rewarding when building something: when people come and tell you the thing you built is great.

**Comment by cheerios911** [comment]
I just sent you an email, may want to check spam as most mail providers don't like our domain name :)

**Comment by kolaente** [comment]
The email arrived perfectly, but my answer got rejected: 

```
<your-email@host.com>: host mail.host.com[192.241.xxx.xxx] said: 554 5.7.1
    Rejected: unauthenticated e-mail from mail.kolaente.de/159.69.89.190 is
    restricted.  Contact the postmaster for details. (in reply to RCPT TO
    command)
```

Is that a configuration error on my side?

**Comment by cheerios911** [comment]
not necessarily a problem on your end, but we have strict mail practices - been getting quite a few attacks since we announced we are releasing a gmail suite, open source competitor.  I'll have my admin tone down our security settings lol.

going to ping your from another account.  one moment

**Comment by kolaente** [comment]
Sent a reply and didn't get a notice from your mailserver back this time, I hope you got it.

**Comment by kolaente** [comment]
Vikunja now has a rudimentary way to subscribe to lists, namespaces or tasks and get notified on actions about it. I'll go ahead and close this issue, feel free to reopen with any suggestions (or send me a mail).
