### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abunet** [go-vikunja/frontend#74]
Hi,
few fix/requests that will make your product awesome, and that (in my case) are blocking the decision to adopt it.
Thanks

- Make le left pane resizable (with long list names there are some problems viewing the text)
- Add Namespace title column in table view
- Add Namespace title on List view (right pane new the List view Title)
- Custom Fields. Add the possibility to add custom fields (Killer_feature)
- the Kanban view is not available in filters when aggregating multiple list

**Comment by dpschen** [comment]
Hello @abunet,

for the first of your items I [created a new ticket](https://kolaente.dev/vikunja/frontend/issues/2396), since I wanted to add some information.

Could you create separate issues for the other items?
It's better for us to have them separated since we are then able to track them individually and merge duplicate items :)

**Comment by kolaente** [comment]
There's a related discussion in the forum about kanban in filters: https://community.vikunja.io/t/unable-to-display-the-kanban-board-for-filters-across-multiple-lists/325

**Comment by abunet** [comment]
Thanks, Closing this, opening #77 #78 #79
